name: auto deploy # workflow name

on:
  [push] # 触发事件

jobs:
  build:
    runs-on: ubuntu-latest # 运行环境为最新版 Ubuntu
    name: auto deploy
    steps:
    - name: Setup Aliyun OSS
      uses: manyuanrong/setup-ossutil@master
      with:
        endpoint: oss-cn-hongkong.aliyuncs.com
        access-key-id: ${{ secrets.OSS_KEY_ID }}
        access-key-secret: ${{ secrets.OSS_KEY_SECRET }}
    - name: Deploy to  Aliyun OSS
      run: ossutil cp -rf ./ oss://xaoxuu-hk-assets/
